### ISSUE TITLE
建议将内网ip段从Poisoned IP中去除

### ISSUE THREAD

**Issue by jue-jue-zi** [Apocalypsor/SmartDNS-GFWList#1]
建议将内网ip段从Poisoned IP中去除，因为很多时候DNS服务器也需要提供对内网服务器的ip解析，如果把全部内网ip的dns解析去除，对于大型内网环境的使用不便利

**Comment by jue-jue-zi** [comment]
已解决：sed -i '/^bogus-nxdomain\ .*$/d'  /etc/smartdns/smartdns-gfw-domain.conf

**Comment by Apocalypsor** [comment]
已修改 25b09ea
