### ISSUE TITLE
请问如何增加ipset的支持

### ISSUE THREAD

**Issue by ixmu** [Apocalypsor/SmartDNS-GFWList#2]
希望实现的功能，smartdns-gfwlist通过指定组dns查询，并加入ipset表

**Comment by Apocalypsor** [comment]
这个项目只是用来防污染的，如果你要添加自己的DNS直接添加
```
server your_dns -blacklist-ip -group GFW -exclude-default-group
```

**Comment by ixmu** [comment]
是的，我用了GFW分组dns进行防污染
发现smartdns有ipset功能，就想把它作为一个分流的准备

**Comment by ixmu** [comment]
> 这个项目只是用来防污染的，如果你要添加自己的DNS直接添加
> 
> ```
> server your_dns -blacklist-ip -group GFW -exclude-default-group
> ```

顺便请问一下这句如何解读

**Comment by Apocalypsor** [comment]
> > 这个项目只是用来防污染的，如果你要添加自己的DNS直接添加
> > ```
> > server your_dns -blacklist-ip -group GFW -exclude-default-group
> > ```
> 
> 顺便请问一下这句如何解读

本项目原理就是把污染的域名用DNS组GFW来解析，属于比较原始的黑名单模式，但是对于DNS污染够了

这句话就是将你自己的DNS加进GFW的DNS组里面，SmartDNS会自动用最快的DNS的，不用担心拖慢速度
